import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "./fonts/fonts";
import {silkscreen} from './fonts/fonts'

export const metadata: Metadata = {
    title: "Informatica Web",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body
                className={`h-full ${montserrat.className} ${silkscreen.variable} antialiased bg-gray-900`}
            >
             
                {children}
            </body>
        </html>
    );
}
