import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "./fonts/fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`w-screen h-screen ${montserrat.className} antialiased h-screen   bg-animated-gradient`}
            >
                {children}
            </body>
        </html>
    );
}
